# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

platform :ios, '16.0'   
use_frameworks!           
inhibit_all_warnings!     

target 'BankApp' do
  pod 'Core', :path => 'Modules/Core'
  pod 'FeatureLogin', :path => 'Modules/FeatureLogin'
  pod 'FeatureAccounts', :path => 'Modules/FeatureAccounts'
  pod 'FeatureCards', :path => 'Modules/FeatureCards'
end
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.resources_build_phase.files.each do |file|
      if file.file_ref && file.file_ref.path.include?("Alamofire.bundle")
        target.resources_build_phase.remove_build_file(file)
      end
    end
  end
end
